// <auto-generated />
using FoodExplorer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodExplorer.Migrations
{
    [DbContext(typeof(FoodExplorerContext))]
    partial class FoodExplorerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("FoodExplorer.Models.Favorite", b =>
                {
                    b.Property<string>("ProductBarCode")
                        .HasColumnType("TEXT");

                    b.Property<long>("AddedDate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductBarCode");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("FoodExplorer.Models.History", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ConsultationDate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductBarCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductBarCode");

                    b.ToTable("HistoryEntries");
                });

            modelBuilder.Entity("FoodExplorer.Models.NutrientLevels", b =>
                {
                    b.Property<string>("ProductBarCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SaturatedFat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sugars")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductBarCode");

                    b.ToTable("NutrientLevels");
                });

            modelBuilder.Entity("FoodExplorer.Models.Product", b =>
                {
                    b.Property<string>("BarCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Additives")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageFrontSmallUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LastUpdatedDate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NutriScore")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Traces")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BarCode");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("FoodExplorer.Models.Favorite", b =>
                {
                    b.HasOne("FoodExplorer.Models.Product", "Product")
                        .WithOne("FavoriteEntry")
                        .HasForeignKey("FoodExplorer.Models.Favorite", "ProductBarCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FoodExplorer.Models.History", b =>
                {
                    b.HasOne("FoodExplorer.Models.Product", "Product")
                        .WithMany("HistoryEntries")
                        .HasForeignKey("ProductBarCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FoodExplorer.Models.NutrientLevels", b =>
                {
                    b.HasOne("FoodExplorer.Models.Product", "Product")
                        .WithOne("NutrientLevels")
                        .HasForeignKey("FoodExplorer.Models.NutrientLevels", "ProductBarCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FoodExplorer.Models.Product", b =>
                {
                    b.Navigation("FavoriteEntry");

                    b.Navigation("HistoryEntries");

                    b.Navigation("NutrientLevels");
                });
#pragma warning restore 612, 618
        }
    }
}
